theme: minima
markdown: kramdown
title: モダンiOSナビゲーションパターン 日本語訳
lang: ja
description: "Modern iOS Navigation Patternsの日本語訳版です。"
author: usagimaru
localhost: "127.0.0.1"
url: "https://usagimaru.github.io"
indexurl: "https://usagimaru.github.io/iOSNavigationPatternsJP"
plugins:
  - jekyll-sitemap
  - jekyll-last-modified-at

# Fix "GitHub Metadata: No GitHub API authentication…" message
github : [metadata]